export const randomItems = [
  {
    name: "Leo",
    type: "animal",
    gender: "male",
    canBeFound: "savannah",
    imageUrl: "",
  },
  {
    name: "Bella",
    type: "animal",
    gender: "female",
    canBeFound: "forest",
    imageUrl: "",
  },
  {
    name: "Speedster",
    type: "vehicle",
    gender: "no gender",
    canBeFound: "racetrack",
    imageUrl: "",
  },
  {
    name: "John",
    type: "person",
    gender: "male",
    canBeFound: "city",
    imageUrl: "",
  },
  {
    name: "Emily",
    type: "person",
    gender: "female",
    canBeFound: "village",
    imageUrl: "",
  },
  {
    name: "Gizmo",
    type: "gadget",
    gender: "no gender",
    canBeFound: "electronics store",
    imageUrl: "",
  },
  {
    name: "Apple",
    type: "fruit",
    gender: "no gender",
    canBeFound: "orchard",
    imageUrl: "",
  },
  {
    name: "Hammer",
    type: "tool",
    gender: "no gender",
    canBeFound: "toolbox",
    imageUrl: "",
  },
  {
    name: "Luna",
    type: "animal",
    gender: "female",
    canBeFound: "mountains",
    imageUrl: "",
  },
  {
    name: "Thunder",
    type: "vehicle",
    gender: "no gender",
    canBeFound: "garage",
    imageUrl: "",
  },
  {
    name: "Alex",
    type: "person",
    gender: "male",
    canBeFound: "university",
    imageUrl: "",
  },
  {
    name: "Sophia",
    type: "person",
    gender: "female",
    canBeFound: "library",
    imageUrl: "",
  },
  {
    name: "Widget",
    type: "gadget",
    gender: "no gender",
    canBeFound: "workshop",
    imageUrl: "",
  },
  {
    name: "Banana",
    type: "fruit",
    gender: "no gender",
    canBeFound: "jungle",
    imageUrl: "",
  },
  {
    name: "Screwdriver",
    type: "tool",
    gender: "no gender",
    canBeFound: "toolbox",
    imageUrl: "",
  },
  {
    name: "Max",
    type: "animal",
    gender: "male",
    canBeFound: "farm",
    imageUrl: "",
  },
  {
    name: "Blazer",
    type: "vehicle",
    gender: "no gender",
    canBeFound: "highway",
    imageUrl: "",
  },
  {
    name: "Luke",
    type: "person",
    gender: "male",
    canBeFound: "gym",
    imageUrl: "",
  },
  {
    name: "Mia",
    type: "person",
    gender: "female",
    canBeFound: "cafe",
    imageUrl: "",
  },
  {
    name: "Doodad",
    type: "gadget",
    gender: "no gender",
    canBeFound: "market",
    imageUrl: "",
  },
  {
    name: "Orange",
    type: "fruit",
    gender: "no gender",
    canBeFound: "grove",
    imageUrl: "",
  },
  {
    name: "Wrench",
    type: "tool",
    gender: "no gender",
    canBeFound: "garage",
    imageUrl: "",
  },
  {
    name: "Daisy",
    type: "animal",
    gender: "female",
    canBeFound: "meadow",
    imageUrl: "",
  },
  {
    name: "Comet",
    type: "vehicle",
    gender: "no gender",
    canBeFound: "spaceport",
    imageUrl: "",
  },
  {
    name: "Ryan",
    type: "person",
    gender: "male",
    canBeFound: "office",
    imageUrl: "",
  },
  {
    name: "Chloe",
    type: "person",
    gender: "female",
    canBeFound: "studio",
    imageUrl: "",
  },
  {
    name: "Contraption",
    type: "gadget",
    gender: "no gender",
    canBeFound: "lab",
    imageUrl: "",
  },
  {
    name: "Peach",
    type: "fruit",
    gender: "no gender",
    canBeFound: "orchard",
    imageUrl: "",
  },
  {
    name: "Drill",
    type: "tool",
    gender: "no gender",
    canBeFound: "construction site",
    imageUrl: "",
  },
  {
    name: "Rocky",
    type: "animal",
    gender: "male",
    canBeFound: "canyon",
    imageUrl: "",
  },
  {
    name: "Shadow",
    type: "animal",
    gender: "male",
    canBeFound: "jungle",
    imageUrl: "",
  },
  {
    name: "Maple",
    type: "person",
    gender: "female",
    canBeFound: "park",
    imageUrl: "",
  },
  {
    name: "Charger",
    type: "vehicle",
    gender: "no gender",
    canBeFound: "parking lot",
    imageUrl: "",
  },
  {
    name: "Nexus",
    type: "gadget",
    gender: "no gender",
    canBeFound: "tech store",
    imageUrl: "",
  },
  {
    name: "Grape",
    type: "fruit",
    gender: "no gender",
    canBeFound: "vineyard",
    imageUrl: "",
  },
  {
    name: "Saw",
    type: "tool",
    gender: "no gender",
    canBeFound: "workshop",
    imageUrl: "",
  },
  {
    name: "Blizzard",
    type: "animal",
    gender: "male",
    canBeFound: "arctic",
    imageUrl: "",
  },
  {
    name: "Skye",
    type: "person",
    gender: "female",
    canBeFound: "beach",
    imageUrl: "",
  },
  {
    name: "Bolt",
    type: "vehicle",
    gender: "no gender",
    canBeFound: "airport",
    imageUrl: "",
  },
  {
    name: "Circuit",
    type: "gadget",
    gender: "no gender",
    canBeFound: "factory",
    imageUrl: "",
  },
  {
    name: "Coconut",
    type: "fruit",
    gender: "no gender",
    canBeFound: "island",
    imageUrl: "",
  },
  {
    name: "Chisel",
    type: "tool",
    gender: "no gender",
    canBeFound: "toolbox",
    imageUrl: "",
  },
  {
    name: "Sable",
    type: "animal",
    gender: "female",
    canBeFound: "tundra",
    imageUrl: "",
  },
  {
    name: "Phoenix",
    type: "person",
    gender: "male",
    canBeFound: "arena",
    imageUrl: "",
  },
  {
    name: "Breeze",
    type: "vehicle",
    gender: "no gender",
    canBeFound: "docks",
    imageUrl: "",
  },
  {
    name: "Quartz",
    type: "gadget",
    gender: "no gender",
    canBeFound: "science center",
    imageUrl: "",
  },
  {
    name: "Lychee",
    type: "fruit",
    gender: "no gender",
    canBeFound: "tropical farm",
    imageUrl: "",
  },
  {
    name: "Jackhammer",
    type: "tool",
    gender: "no gender",
    canBeFound: "construction site",
    imageUrl: "",
  },
  {
    name: "Frost",
    type: "animal",
    gender: "male",
    canBeFound: "glacier",
    imageUrl: "",
  },
  {
    name: "Cedar",
    type: "person",
    gender: "female",
    canBeFound: "forest cabin",
    imageUrl: "",
  },
  {
    name: "Neon",
    type: "vehicle",
    gender: "no gender",
    canBeFound: "city street",
    imageUrl: "",
  },
  {
    name: "Flux",
    type: "gadget",
    gender: "no gender",
    canBeFound: "energy lab",
    imageUrl: "",
  },
  {
    name: "Mango",
    type: "fruit",
    gender: "no gender",
    canBeFound: "tropical island",
    imageUrl: "",
  },
  {
    name: "Spanner",
    type: "tool",
    gender: "no gender",
    canBeFound: "tool shed",
    imageUrl: "",
  },
  {
    name: "Zephyr",
    type: "animal",
    gender: "female",
    canBeFound: "prairie",
    imageUrl: "",
  },
  {
    name: "Atlas",
    type: "person",
    gender: "male",
    canBeFound: "museum",
    imageUrl: "",
  },
  {
    name: "Falcon",
    type: "vehicle",
    gender: "no gender",
    canBeFound: "hangar",
    imageUrl: "",
  },
  {
    name: "Radar",
    type: "gadget",
    gender: "no gender",
    canBeFound: "military base",
    imageUrl: "",
  },
  {
    name: "Papaya",
    type: "fruit",
    gender: "no gender",
    canBeFound: "garden",
    imageUrl: "",
  },
  {
    name: "Anvil",
    type: "tool",
    gender: "no gender",
    canBeFound: "blacksmith shop",
    imageUrl: "",
  },
  {
    name: "Raven",
    type: "animal",
    gender: "male",
    canBeFound: "castle",
    imageUrl: "",
  },
  {
    name: "Hazel",
    type: "person",
    gender: "female",
    canBeFound: "meadow",
    imageUrl: "",
  },
  {
    name: "Monsoon",
    type: "vehicle",
    gender: "no gender",
    canBeFound: "harbor",
    imageUrl: "",
  },
  {
    name: "Microchip",
    type: "gadget",
    gender: "no gender",
    canBeFound: "tech company",
    imageUrl: "",
  },
  {
    name: "Blueberry",
    type: "fruit",
    gender: "no gender",
    canBeFound: "field",
    imageUrl: "",
  },
  {
    name: "Hatchet",
    type: "tool",
    gender: "no gender",
    canBeFound: "cabin",
    imageUrl: "",
  },
];
