export const randomItems = [
  {
    name: "Mystic Wand",
    type: "Arcane",
    gender: "unisex",
    canBeFound: "Mystic Forest",
    star: "fivestar",
    weapon: "Wand",
    imageUrl: "",
  },
  {
    name: "Flame Dagger",
    type: "Pyro",
    gender: "unisex",
    canBeFound: "Volcanic Caves",
    star: "fourstar",
    weapon: "Dagger",
    imageUrl: "",
  },
  {
    name: "Eleanor the Herbalist",
    type: "Healer",
    gender: "female",
    canBeFound: "Mystic Forest",
    star: "fourstar",
    weapon: "No Weapon",
    imageUrl: "",
  },
  {
    name: "Gregor the Blacksmith",
    type: "Melee Expert",
    gender: "male",
    canBeFound: "Blacksmith's Forge",
    star: "fivestar",
    weapon: "Hammer",
    imageUrl: "",
  },
  {
    name: "Runed Pendant",
    type: "Magic",
    gender: "unisex",
    canBeFound: "Library of Secrets",
    star: "fivestar",
    weapon: "No Weapon",
    imageUrl: "",
  },
  {
    name: "Ariella the Librarian",
    type: "Magic Researcher",
    gender: "female",
    canBeFound: "Library of Secrets",
    star: "fivestar",
    weapon: "No Weapon",
    imageUrl: "",
  },
  {
    name: "Lena the Scout",
    type: "Stealth Specialist",
    gender: "female",
    canBeFound: "Thieves' Guild",
    star: "fourstar",
    weapon: "Dagger",
    imageUrl: "",
  },
  {
    name: "Milo the Tracker",
    type: "Arcane Hunter",
    gender: "male",
    canBeFound: "Mystic Forest",
    star: "fivestar",
    weapon: "Bow",
    imageUrl: "",
  },
  {
    name: "Aiden the Outcast",
    type: "Cryo Warrior",
    gender: "male",
    canBeFound: "Frozen Tundra",
    star: "fivestar",
    weapon: "Sword",
    imageUrl: "",
  },
  {
    name: "Sienna the Pyromancer",
    type: "Pyro Mage",
    gender: "female",
    canBeFound: "Volcanic Caves",
    star: "fivestar",
    weapon: "Staff",
    imageUrl: "",
  },
  {
    name: "Talia the Alchemist",
    type: "Arcane Researcher",
    gender: "female",
    canBeFound: "Library of Secrets",
    star: "fourstar",
    weapon: "Orb",
    imageUrl: "",
  },
  {
    name: "Ronan the Warrior",
    type: "Melee",
    gender: "male",
    canBeFound: "Blacksmith's Forge",
    star: "fourstar",
    weapon: "Sword",
    imageUrl: "",
  },
  {
    name: "Nina the Navigator",
    type: "Explorer",
    gender: "female",
    canBeFound: "Stormy Peaks",
    star: "fourstar",
    weapon: "No Weapon",
    imageUrl: "",
  },
  {
    name: "Kael the Frost Archer",
    type: "Cryo Archer",
    gender: "male",
    canBeFound: "Frozen Tundra",
    star: "fivestar",
    weapon: "Bow",
    imageUrl: "",
  },
  {
    name: "Levi the Shadowblade",
    type: "Stealth Fighter",
    gender: "male",
    canBeFound: "Thieves' Guild",
    star: "fivestar",
    weapon: "Dagger",
    imageUrl: "",
  },
  {
    name: "Seraphina the Seer",
    type: "Magic Diviner",
    gender: "female",
    canBeFound: "Library of Secrets",
    star: "fivestar",
    weapon: "Crystal Ball",
    imageUrl: "",
  },
  {
    name: "Ezra the Mechanic",
    type: "Inventor",
    gender: "male",
    canBeFound: "Blacksmith's Forge",
    star: "fourstar",
    weapon: "Hammer",
    imageUrl: "",
  },
  {
    name: "Isla the Tamer",
    type: "Beast Master",
    gender: "female",
    canBeFound: "Mystic Forest",
    star: "fourstar",
    weapon: "No Weapon",
    imageUrl: "",
  },
  {
    name: "Dante the Rogue",
    type: "Stealth Operative",
    gender: "male",
    canBeFound: "Thieves' Guild",
    star: "fourstar",
    weapon: "Dagger",
    imageUrl: "",
  },
  {
    name: "Amara the Pyro Healer",
    type: "Pyro",
    gender: "female",
    canBeFound: "Volcanic Caves",
    star: "fivestar",
    weapon: "Wand",
    imageUrl: "",
  },
  {
    name: "Lucian the Stormbringer",
    type: "Electro",
    gender: "male",
    canBeFound: "Stormy Peaks",
    star: "fivestar",
    weapon: "Sword",
    imageUrl: "",
  },
  {
    name: "Vivienne the Frost Mage",
    type: "Cryo Mage",
    gender: "female",
    canBeFound: "Frozen Tundra",
    star: "fivestar",
    weapon: "Staff",
    imageUrl: "",
  },
  {
    name: "Orion the Nomad",
    type: "Arcane Wanderer",
    gender: "male",
    canBeFound: "Mystic Forest",
    star: "fourstar",
    weapon: "No Weapon",
    imageUrl: "",
  },
  {
    name: "Juno the Archivist",
    type: "Magic Historian",
    gender: "female",
    canBeFound: "Library of Secrets",
    star: "fourstar",
    weapon: "No Weapon",
    imageUrl: "",
  },
  {
    name: "Raelyn the Forger",
    type: "Melee Specialist",
    gender: "female",
    canBeFound: "Blacksmith's Forge",
    star: "fourstar",
    weapon: "Hammer",
    imageUrl: "",
  },
  {
    name: "Zane the Lightning Runner",
    type: "Electro",
    gender: "male",
    canBeFound: "Stormy Peaks",
    star: "fivestar",
    weapon: "Spear",
    imageUrl: "",
  },
  {
    name: "Camille the Frost Hunter",
    type: "Cryo Archer",
    gender: "female",
    canBeFound: "Frozen Tundra",
    star: "fourstar",
    weapon: "Bow",
    imageUrl: "",
  },
  {
    name: "Ivy the Wildling",
    type: "Beast Tamer",
    gender: "female",
    canBeFound: "Mystic Forest",
    star: "fourstar",
    weapon: "No Weapon",
    imageUrl: "",
  },
  {
    name: "Ezekiel the Wanderer",
    type: "Nomad",
    gender: "male",
    canBeFound: "Stormy Peaks",
    star: "fourstar",
    weapon: "No Weapon",
    imageUrl: "",
  },
];
