export const people = [
  {
    name: "Alice Johnson",
    imageUrl: "",
    yearLevel: 2,
    averageGrade: 85,
    gender: "Female",
    height: 165,
  },
  {
    name: "Michael Smith",
    imageUrl: "",
    yearLevel: 3,
    averageGrade: 78,
    gender: "Male",
    height: 180,
  },
  {
    name: "Sophia Brown",
    imageUrl: "",
    yearLevel: 1,
    averageGrade: 92,
    gender: "Female",
    height: 158,
  },
  {
    name: "James Davis",
    imageUrl: "",
    yearLevel: 4,
    averageGrade: 70,
    gender: "Male",
    height: 175,
  },
  {
    name: "Emma Wilson",
    imageUrl: "",
    yearLevel: 2,
    averageGrade: 88,
    gender: "Female",
    height: 162,
  },
  {
    name: "William Martinez",
    imageUrl: "",
    yearLevel: 3,
    averageGrade: 83,
    gender: "Male",
    height: 172,
  },
  {
    name: "Olivia Garcia",
    imageUrl: "",
    yearLevel: 1,
    averageGrade: 91,
    gender: "Female",
    height: 160,
  },
  {
    name: "Benjamin Anderson",
    imageUrl: "",
    yearLevel: 4,
    averageGrade: 76,
    gender: "Male",
    height: 177,
  },
  {
    name: "Mia Taylor",
    imageUrl: "",
    yearLevel: 2,
    averageGrade: 89,
    gender: "Female",
    height: 163,
  },
  {
    name: "Lucas Thomas",
    imageUrl: "",
    yearLevel: 3,
    averageGrade: 81,
    gender: "Male",
    height: 182,
  },
  {
    name: "Charlotte Moore",
    imageUrl: "",
    yearLevel: 1,
    averageGrade: 95,
    gender: "Female",
    height: 157,
  },
  {
    name: "Henry White",
    imageUrl: "",
    yearLevel: 4,
    averageGrade: 74,
    gender: "Male",
    height: 179,
  },
  {
    name: "Amelia Harris",
    imageUrl: "",
    yearLevel: 2,
    averageGrade: 87,
    gender: "Female",
    height: 164,
  },
  {
    name: "Noah Clark",
    imageUrl: "",
    yearLevel: 3,
    averageGrade: 80,
    gender: "Male",
    height: 176,
  },
  {
    name: "Isabella Lewis",
    imageUrl: "",
    yearLevel: 1,
    averageGrade: 93,
    gender: "Female",
    height: 159,
  },
  {
    name: "Jack Walker",
    imageUrl: "",
    yearLevel: 4,
    averageGrade: 72,
    gender: "Male",
    height: 181,
  },
  {
    name: "Grace Hall",
    imageUrl: "",
    yearLevel: 2,
    averageGrade: 86,
    gender: "Female",
    height: 161,
  },
  {
    name: "Ethan Young",
    imageUrl: "",
    yearLevel: 3,
    averageGrade: 82,
    gender: "Male",
    height: 178,
  },
  {
    name: "Ava King",
    imageUrl: "",
    yearLevel: 1,
    averageGrade: 90,
    gender: "Female",
    height: 156,
  },
  {
    name: "Alexander Wright",
    imageUrl: "",
    yearLevel: 4,
    averageGrade: 75,
    gender: "Male",
    height: 174,
  },
];
