async function getData() {
  try {
    if (responseTypes.status != 200) {
      throw new Error(responseTypes);
    }
  } catch (error) {}
}

export const randomItems = [
  {
    name: "Amber",
    type: "Pyro",
    gender: "female",
    canBeFound: "Mondstadt",
    star: "fourstar",
    weapon: "Bow",
    imageUrl: "",
  },
  {
    name: "Kaeya",
    type: "Cryo",
    gender: "male",
    canBeFound: "Mondstadt",
    star: "fourstar",
    weapon: "Sword",
    imageUrl: "",
  },
  {
    name: "Lisa",
    type: "Electro",
    gender: "female",
    canBeFound: "Mondstadt",
    star: "fourstar",
    weapon: "Catalyst",
    imageUrl: "",
  },
  {
    name: "Diluc",
    type: "Pyro",
    gender: "male",
    canBeFound: "Mondstadt",
    star: "fivestar",
    weapon: "Claymore",
    imageUrl: "",
  },
  {
    name: "Jean",
    type: "Anemo",
    gender: "female",
    canBeFound: "Mondstadt",
    star: "fivestar",
    weapon: "Sword",
    imageUrl: "",
  },
  {
    name: "Barbara",
    type: "Hydro",
    gender: "female",
    canBeFound: "Mondstadt",
    star: "fourstar",
    weapon: "Catalyst",
    imageUrl: "",
  },
  {
    name: "Albedo",
    type: "Geo",
    gender: "male",
    canBeFound: "Mondstadt",
    star: "fivestar",
    weapon: "Sword",
    imageUrl: "",
  },
  {
    name: "Aloy",
    type: "Cryo",
    gender: "female",
    canBeFound: "Mondstadt",
    star: "fivestar",
    weapon: "Bow",
    imageUrl: "",
  },
  {
    name: "Xiangling",
    type: "Pyro",
    gender: "female",
    canBeFound: "Liyue",
    star: "fourstar",
    weapon: "Polearm",
    imageUrl: "",
  },
  {
    name: "Xiao",
    type: "Anemo",
    gender: "male",
    canBeFound: "Liyue",
    star: "fivestar",
    weapon: "Polearm",
    imageUrl: "",
  },
  {
    name: "Ningguang",
    type: "Geo",
    gender: "female",
    canBeFound: "Liyue",
    star: "fourstar",
    weapon: "Catalyst",
    imageUrl: "",
  },
  {
    name: "Zhongli",
    type: "Geo",
    gender: "male",
    canBeFound: "Liyue",
    star: "fivestar",
    weapon: "Polearm",
    imageUrl: "",
  },
  {
    name: "Beidou",
    type: "Electro",
    gender: "female",
    canBeFound: "Liyue",
    star: "fourstar",
    weapon: "Claymore",
    imageUrl: "",
  },
  {
    name: "Ganyu",
    type: "Cryo",
    gender: "female",
    canBeFound: "Liyue",
    star: "fivestar",
    weapon: "Bow",
    imageUrl: "",
  },
  {
    name: "Tartaglia",
    type: "Hydro",
    gender: "male",
    canBeFound: "Snezhnaya",
    star: "fivestar",
    weapon: "Bow",
    imageUrl: "",
  },
  {
    name: "Raiden Shogun",
    type: "Electro",
    gender: "female",
    canBeFound: "Inazuma",
    star: "fivestar",
    weapon: "Polearm",
    imageUrl: "",
  },
  {
    name: "Kamisato Ayaka",
    type: "Cryo",
    gender: "female",
    canBeFound: "Inazuma",
    star: "fivestar",
    weapon: "Sword",
    imageUrl: "",
  },
  {
    name: "Kamisato Ayato",
    type: "Hydro",
    gender: "male",
    canBeFound: "Inazuma",
    star: "fivestar",
    weapon: "Sword",
    imageUrl: "",
  },
  {
    name: "Thoma",
    type: "Pyro",
    gender: "male",
    canBeFound: "Inazuma",
    star: "fourstar",
    weapon: "Polearm",
    imageUrl: "",
  },
  {
    name: "Yae Miko",
    type: "Electro",
    gender: "female",
    canBeFound: "Inazuma",
    star: "fivestar",
    weapon: "Catalyst",
    imageUrl: "",
  },
  {
    name: "Nahida",
    type: "Dendro",
    gender: "female",
    canBeFound: "Sumeru",
    star: "fivestar",
    weapon: "Catalyst",
    imageUrl: "",
  },
  {
    name: "Alhaitham",
    type: "Dendro",
    gender: "male",
    canBeFound: "Sumeru",
    star: "fivestar",
    weapon: "Sword",
    imageUrl: "",
  },
  {
    name: "Tighnari",
    type: "Dendro",
    gender: "male",
    canBeFound: "Sumeru",
    star: "fivestar",
    weapon: "Bow",
    imageUrl: "",
  },
  {
    name: "Dehya",
    type: "Pyro",
    gender: "female",
    canBeFound: "Sumeru",
    star: "fivestar",
    weapon: "Claymore",
    imageUrl: "",
  },
  {
    name: "Furina",
    type: "Hydro",
    gender: "female",
    canBeFound: "Fontaine",
    star: "fivestar",
    weapon: "Sword",
    imageUrl: "",
  },
  {
    name: "Neuvillette",
    type: "Hydro",
    gender: "male",
    canBeFound: "Fontaine",
    star: "fivestar",
    weapon: "Catalyst",
    imageUrl: "",
  },
  {
    name: "Lynette",
    type: "Anemo",
    gender: "female",
    canBeFound: "Fontaine",
    star: "fourstar",
    weapon: "Sword",
    imageUrl: "",
  },
  {
    name: "Lyney",
    type: "Pyro",
    gender: "male",
    canBeFound: "Fontaine",
    star: "fivestar",
    weapon: "Bow",
    imageUrl: "",
  },
];
